import assert from 'node:assert/strict';
import {compile,execute} from './dist/runtime.mjs';
import {examples,virtualSketch} from './dist/examples.mjs';
import {checkCircuit,lessonWires,validateProject,newPartsForLesson,keepWiresFromPreviousLessons,wireTouchesPart,newWiresForLesson,previousWiresForLesson} from './dist/circuit.mjs';
import {footprint,placement} from './dist/breadboard.mjs';
import {Display} from './dist/display.mjs';
for(const [name,code] of Object.entries(examples)){
  const src=/ESP_I2S|I2SClass/.test(code)?virtualSketch(code):code;
  assert.ok(compile(src),name);
}
assert.ok(examples.dino_jump&&examples.star_catch&&examples.clap_mole);
assert.match(virtualSketch(examples.dino_jump),/DINO/);
assert.match(virtualSketch(examples.star_catch),/STAR/);
assert.match(virtualSketch(examples.clap_mole),/MOLE/);
for(const code of ['void setup(){}','void setup(){bad();}void loop(){}','void setup(){delay();}void loop(){}','#include <ESP_I2S.h>\nvoid setup(){}void loop(){}','void setup(){int x=;}void loop(){}'])assert.throws(()=>compile(code));
const wires=lessonWires.map(([a,b])=>({a,b}));
assert.equal(checkCircuit(wires,['esp','oled']).ready,true);
assert.equal(checkCircuit(wires.slice(1),['esp','oled']).ready,false);
assert.equal(checkCircuit(wires,['esp','oled'],4,5).ready,false);
assert.ok(checkCircuit([...wires,{a:'esp:G',b:'esp:3.3'}],['esp','oled']).errors.length);
assert.throws(()=>validateProject({version:1,code:'',parts:[],wires:[{a:'bogus',b:'esp:G'}]}));
assert.deepEqual(newPartsForLesson(1),['esp','oled']);
assert.deepEqual(newPartsForLesson(2),['amp','speaker']);
assert.deepEqual(newPartsForLesson(3),['mic']);
const board=['esp','oled','amp','speaker','mic'].map(id=>placement(id));
const hole=(id,pin)=>footprint(id,board.find(p=>p.id===id).row).find(e=>e.a===id+':'+pin).b;
const oledGnd={a:hole('oled','GND'),b:hole('esp','G')};
const oledSda={a:hole('oled','SDA'),b:hole('esp','5')};
const ampGnd={a:hole('amp','GND'),b:hole('esp','G')};
const micSd={a:hole('mic','SD'),b:hole('esp','10')};
assert.equal(wireTouchesPart(ampGnd,'amp',board),true);
assert.equal(wireTouchesPart(oledGnd,'amp',board),false);
assert.equal(wireTouchesPart(oledGnd,'oled',board),true);
const kept2=keepWiresFromPreviousLessons([oledGnd,oledSda,ampGnd],2,board);
assert.equal(kept2.length,2);
assert.ok(kept2.includes(oledGnd)&&kept2.includes(oledSda));
assert.ok(!kept2.includes(ampGnd));
const kept3=keepWiresFromPreviousLessons([oledGnd,ampGnd,micSd],3,board);
assert.equal(kept3.length,2);
assert.ok(kept3.includes(oledGnd)&&kept3.includes(ampGnd));
assert.ok(!kept3.includes(micSd));
assert.deepEqual(keepWiresFromPreviousLessons([oledGnd],1,board),[]);
assert.equal(previousWiresForLesson(1).length,0);
assert.equal(newWiresForLesson(1).length,4);
assert.equal(previousWiresForLesson(2).length,4);
assert.equal(newWiresForLesson(2).length,5);
assert.ok(newWiresForLesson(2).every(w=>w[0].startsWith('amp:')));
assert.equal(previousWiresForLesson(3).length,9);
assert.equal(newWiresForLesson(3).length,5);
assert.ok(newWiresForLesson(3).every(w=>w[0].startsWith('mic:')));
const d=new Display();d.circle(40,32,14,1,true);assert.equal(d.pixels[32*128+40],1);assert.equal(d.pixels[0],0);
const controller=new AbortController(),calls=[];
try{await execute(compile('void setup(){}void loop(){for(int x=0;x<3;x++){Serial.println(x);}delay(1);}'),{call(n,a){calls.push([n,...a]);if(calls.length===3)controller.abort();}},controller.signal);}catch(e){assert.equal(e.message,'STOPPED');}
assert.deepEqual(calls,[['Serial.println',0],['Serial.println',1],['Serial.println',2]]);
const stop=new AbortController();setTimeout(()=>stop.abort(),20);await assert.rejects(execute(compile('void setup(){}void loop(){while(true){}}'),{call(){}},stop.signal),/STOPPED/);
console.log('PASS: examples, syntax errors, unsupported libraries, wiring, shorts, pixels, loop execution and cancellation');
